# Generated by Django 5.1.3 on 2024-11-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='preguntas',
            field=models.JSONField(default=list),
        ),
    ]
